FROM alpine:20250108
RUN apk add --no-cache \
  bash=5.2.37-r0 \
  ca-certificates=20241121-r2 \
  curl=8.15.0-r0 \
  gzip=1.14-r2 \
  make=4.4.1-r3 \
  tar=1.35-r4 \
  unzip=6.0-r16 \
  wget=1.25.0-r2
WORKDIR /tmp