FROM alpine:20240807
RUN apk add --no-cache \
  bash=5.2.32-r0 \
  ca-certificates=20240705-r0 \
  curl=8.9.1-r2 \
  gzip=1.13-r0 \
  make=4.4.1-r2 \
  tar=1.35-r2 \
  unzip=6.0-r15 \
  wget=1.24.5-r0
WORKDIR /tmp